//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reportes_de_Victor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int PagoId { get; set; }
        public int PrestamoId { get; set; }
        public int NumeroMes { get; set; }
        public decimal MontoAnterior { get; set; }
        public decimal InteresAPagar { get; set; }
        public decimal NuevoMontoDeber { get; set; }
        public decimal Cuota { get; set; }
        public int MesesRestantes { get; set; }
        public decimal TotalAcumuladoIntereses { get; set; }
        public decimal TasaPrestamo { get; set; }
        public decimal Mora { get; set; }
        public bool Pagado { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Prestamos Prestamos { get; set; }
    }
}
